### ISSUE TITLE
Nest js - fireorm - errors when run docker image

### ISSUE THREAD

**Issue by DiegoAsadurian** [glebbash/nestjs-fireorm#13]
Hello, how are you?
I'm having these errors when running my deployed nest js api.
Locally everything works perfectly, but after generating the docker image, and running it locally or pointing to the deploy, when I try to log in I get these errors.

I think this started to happen after I added the firebase functions to my project, in which I only configured triggers.

I've already updated the dependencies and they're all the same, and I can't figure out where the error might be.

Since it only throws these errors when I run the deployed api or pointing to the docker image.

If someone has had something similar happen to them, I look forward to your response.

Thank you very much.

[Nest] 60  - 08/29/2024, 2:34:59 PM   ERROR [ExceptionsHandler] "length" is outside of buffer bounds
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: "length" is outside of buffer bounds
    at proto.utf8Write (node:internal/buffer:1066:13)
    at Op.writeStringBuffer [as fn] (/app/node_modules/protobufjs/src/writer_buffer.js:61:13)
    at BufferWriter.finish (/app/node_modules/protobufjs/src/writer.js:453:14)
    at <anonymous> (/app/node_modules/@grpc/proto-loader/src/index.ts:382:62)
    at Array.map (<anonymous>)
    at createPackageDefinition (/app/node_modules/@grpc/proto-loader/src/index.ts:381:47)
    at Object.fromJSON (/app/node_modules/@grpc/proto-loader/src/index.ts:453:10)
    at GrpcClient.loadProtoJSON (/app/node_modules/google-gax/build/src/grpc.js:228:51)
    at new LocationsClient (/app/node_modules/google-gax/build/src/locationService.js:118:32)
    at new FirestoreClient (/app/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:136:32)
Caused by: Error
    at QueryUtil._getResponse (/app/node_modules/@google-cloud/firestore/build/src/reference/query-util.js:42:23)
    at Query._getResponse (/app/node_modules/@google-cloud/firestore/build/src/reference/query.js:792:32)
    at Query._get (/app/node_modules/@google-cloud/firestore/build/src/reference/query.js:785:35)
    at Query.get (/app/node_modules/@google-cloud/firestore/build/src/reference/query.js:754:39)
    at BaseFirestoreRepository.<anonymous> (/app/node_modules/fireorm/lib/src/BaseFirestoreRepository.js:216:57)
    at step (/app/node_modules/fireorm/lib/src/BaseFirestoreRepository.js:67:23)
    at Object.next (/app/node_modules/fireorm/lib/src/BaseFirestoreRepository.js:48:53)
    at /app/node_modules/fireorm/lib/src/BaseFirestoreRepository.js:42:71
    at new Promise (<anonymous>)

**Comment by DiegoAsadurian** [comment]
The problem was with the node version of the docker file
